#!/usr/bin/ruby

class GitNum
  class << self
    def parse_args(args)
      if args[0] == 'convert'
        convert(args.drop(1))
      end
    end

    private

    def convert(indexes)
      filenames = filenames_by_index
      print indexes.map { |index| filenames[index] || index }.join(' ')
    end

    def filenames_by_index
      i = 0
      git_status_porcelain.split("\n").reduce({}) do |filenames, status_line|
        i += 1
        filenames[i.to_s] = status_line[3..-1]
        filenames
      end
    end

    def git_status_porcelain
      `git status --porcelain`
    end
  end
end

if __FILE__ == $PROGRAM_NAME
  GitNum.parse_args(ARGV)
end
