def colorize(section, str)
  i = case section
      when :added
        ADDED_COLOR_CODE
      when :changed
        CHANGED_COLOR_CODE
      when :untracked
        UNTRACKED_COLOR_CODE
      else
        raise "Unknown section: #{section}"
      end

  "\e[#{i}m#{str}\e[m"
end

# The FIXTURES data structure is built from static files generated by
# `support/generate_fixtures.rb`. The object looks like this:
#
#    {
#      (description of the fixture) => {
#        git_status: "...",      # output of `git status`
#        annotated_status: "..." # expected output of `git num` given `git status`
#      },
#      ...
#    }
FIXTURES = {}
Dir.glob('spec/fixtures/*') do |filename|
  fixture_name = filename.sub('spec/fixtures/', '').sub('_annotated', '').to_sym
  fixture_type = filename.end_with?('_annotated') ? :annotated_status : :git_status

  FIXTURES[fixture_name] ||= {}
  FIXTURES[fixture_name][fixture_type] = File.read(filename)
end
FIXTURES.freeze
